### PR TITLE
Chess: Updated manpage with simple description of the game

### PR DESCRIPTION
**Pull request by spraines**
Updated the Chess manpage with a descriptor to be more in line with the other games.

### CODE REVIEW

**Comment by awesomekling** [comment]
This repository contains files generated automatically from the sources in https://github.com/SerenityOS/serenity
Please make your changes there instead, and they will be reflected here automatically when merged. :^)

**Comment by spraines** [comment]
> This repository contains files generated automatically from the sources in https://github.com/SerenityOS/serenity Please make your changes there instead, and they will be reflected here automatically when merged. :^)

Apologies for this, where are the HTML files within there? Or do I make the changes to the .md files?

**Comment by awesomekling** [comment]
> > This repository contains files generated automatically from the sources in [SerenityOS/serenity](https://github.com/SerenityOS/serenity) Please make your changes there instead, and they will be reflected here automatically when merged. :^)
> 
> Apologies for this, where are the HTML files within there? Or do I make the changes to the .md files?

No worries! That's right, you'll need to edit the .md files :)

**Comment by spraines** [comment]
> > > This repository contains files generated automatically from the sources in [SerenityOS/serenity](https://github.com/SerenityOS/serenity) Please make your changes there instead, and they will be reflected here automatically when merged. :^)
> > 
> > 
> > Apologies for this, where are the HTML files within there? Or do I make the changes to the .md files?
> 
> No worries! That's right, you'll need to edit the .md files :)

Ok, thank you so much!

**Pull request closed without merging**
